Zuricon/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('favigen.urls', namespace='fav')),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('favigen.urls', namespace='fav')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

favigen/urls.py
from django.urls import path
from . import views

app_name = "favigen"

urlpatterns = [
    path("", views.home_page, name="home"),
    path("signup/", views.signup_page, name="signup"),
    path("login/", views.login_page, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("contact/", views.contact_page, name="contact"),
    path("message-sent/", views.message_sent, name="sent"),
    path("saved-icons/", views.saved_icons, name="saved"),
    path("generated-icon/<str:pk>", views.generated_icon, name="generated"),
    path("generate-icon/", views.generate_icon, name="generate"),
]

favigen/models.py
from ast import Try
from tabnanny import verbose
from django.db import models
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _

from .managers import CustomUserManager
from .utils.utility import user_directory_path

User = settings.AUTH_USER_MODEL


class CustomUser(AbstractUser):
    username = None
    email = models.EmailField(verbose_name=_('email address'), unique=True)
    first_name = models.CharField(max_length=50, blank=True, null=True)
    last_name = models.CharField(max_length=50, blank=True, null=True)

    # full_name = models.CharField(max_length=255, blank=True, null=True)
    # slug = models.SlugField(blank=True, unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name']

    objects = CustomUserManager()

    class Meta:
        ordering = ['email']
        verbose_name = 'User'

    def __str__(self):
        return self.email
    
    def get_full_name(self) -> str:
        return super().get_full_name()

    def get_short_name(self) -> str:
        return super().get_short_name()


class Image(models.Model):
    title = models.CharField(max_length=100, null=True)
    uploaded_image = models.ImageField(upload_to=user_directory_path, blank=True, null=True)
    favourite = models.BooleanField(default=False)
    uploaded_by = models.ForeignKey(to=User, on_delete=models.CASCADE, related_name='image_info')
    uploaded_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class Favicon(models.Model):
    image = models.OneToOneField(to=Image, null=True, on_delete=models.CASCADE)
    original_filename = models.CharField(max_length=256, null=True)
    new_filename = models.CharField(max_length=256, null=True)
    zipped_favs = models.FileField(blank=True, null=True)
    file_type = models.CharField(max_length=10, null=True)
    file_byte_size = models.IntegerField(default=0)
    embed_link = models.TextField(null=True)

    def __str__(self):
        return self.new_filename


class Message(models.Model):
    PRIORITY_LEVELS = (
        ("critical", "Critical"),
        ("major", "Major"),
        ("medium", "Medium"),
        ("minor", "Minor")
    )
    title = models.CharField(max_length=256, null=True)
    user = models.ForeignKey(to=User, on_delete=models.SET_NULL, null=True)
    email = models.EmailField(verbose_name=_('email address'))
    message = models.TextField()
    priority = models.CharField(max_length=10, choices=PRIORITY_LEVELS, default="minor")
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

favigen/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm
from django.contrib.auth import authenticate
from django import forms
from .models import CustomUser, Favicon


class CustomUserCreationForm(UserCreationForm):

    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        self.fields["first_name"].widget.attrs.update({
            'input type':'text',
            'id': 'firstName',
            'name': 'first_name',
            'placeholder': 'First Name'
        })
        self.fields["email"].widget.attrs.update({
            'input type':'email',
            'id': 'email',
            'name': 'email',
            'placeholder': 'Email Address'
        })
        self.fields["password1"].widget.attrs.update({
            'type':'password',
            'id': 'password',
            'name': 'password',
            'placeholder': 'Password'
        })
        self.fields["password2"].widget.attrs.update({
            'type':'password',
            'id': 'password',
            'name': 'password',
            'placeholder': 'Password again'
        })


    class Meta:
        model = CustomUser
        fields = ('email', 'first_name', 'last_name')


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('email', 'first_name', 'last_name')


class CustomAuthenticationForm(forms.ModelForm):
    """
      Form for Logging in  users
    """
    password  = forms.CharField(label= 'Password', widget=forms.PasswordInput)

    class Meta:
        model  =  CustomUser
        fields =  ('email', 'password')
        widgets = {
                   'email':forms.TextInput(attrs={'class':'form-control'}),
                   'password':forms.TextInput(attrs={'class':'form-control'}),
        }
    def __init__(self, *args, **kwargs):
        """
          specifying styles to fields 
        """
        super(CustomAuthenticationForm, self).__init__(*args, **kwargs)
        self.fields["email"].widget.attrs.update({
            'class':'form-inpu',
            'id': 'email',
            'type': 'email',
            'placeholder': 'Email'
        })
        self.fields["password"].widget.attrs.update({
            'class':'form-input',
            'id': 'password',
            'type': 'password',
            'placeholder': 'Password'
        })

    def clean(self):
        if self.is_valid():

            email = self.cleaned_data.get('email')
            password = self.cleaned_data.get('password')
            if not authenticate(email=email, password=password):
                raise forms.ValidationError('Invalid Login')


# class HotelForm(forms.ModelForm):
  
#     class Meta:
#         model = Favicon
#         fields = ['name', 'hotel_Main_Img']





# class AccountUpdateform(forms.ModelForm):
#     """
#       Updating User Info
#     """
#     class Meta:
#         model  = CustomUser
#         fields = ('email', 'username')
#         widgets = {
#                    'email':forms.TextInput(attrs={'class':'form-control'}),
#                    'password':forms.TextInput(attrs={'class':'form-control'}),
#         }

#     def __init__(self, *args, **kwargs):
#         """
#           specifying styles to fields 
#         """
#         super(AccountUpdateform, self).__init__(*args, **kwargs)
#         for field in (self.fields['email'],self.fields['username']):
#             field.widget.attrs.update({'class': 'form-control '})

#     def clean_email(self):
#         if self.is_valid():
#             email = self.cleaned_data['email']
#             try:
#                 account = CustomUser.objects.exclude(pk = self.instance.pk).get(email=email)
#             except CustomUser.DoesNotExist:
#                 return email
#             raise forms.ValidationError("Email '%s' already in use." %email)
#     def clean_username(self):
#         if self.is_valid():
#             username = self.cleaned_data['username']
#             try:
#                 account = CustomUser.objects.exclude(pk = self.instance.pk).get(username=username)
#             except CustomUser.DoesNotExist:
#                 return username
#             raise forms.ValidationError("Username '%s' already in use." % username)

favigen/views.py
from datetime import datetime
from django.shortcuts import render
from django.core.files import File
from django.core.files.storage import FileSystemStorage

from django.contrib import messages
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, logout, authenticate
from favigen.forms import CustomUserCreationForm, CustomAuthenticationForm

from pathlib import Path
from .models import *
from .utils import zippify
from .utils import utility
from .utils.favigenerator import generate_favicon

import os
import re

# Create your views here.
def home_page(request):
    return render(request, "favigen/home.html")


def signup_page(request):
    """
    This view renders the signup page and then takes in user data 
    (First Name, Email and Password) from the HTML form as a POST request.
    It then extracts the user's first name from the form and uses it in a 
    custom message if the registration is successful, after which it 
    redirects the user to the home page.
    """
    if not request.user.is_anonymous:
        return redirect("favigen:home")

    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            f_name = form.cleaned_data.get("first_name")
            messages.success(request, f"Registration successful for {f_name}")
            return redirect("favigen:home")
        messages.error(request, "Unsuccessful registration. Invalid information.")

    form = CustomUserCreationForm()
    return render(
        request=request,
        template_name="favigen/sign-up.html",
        context={"signup_form": form},
    )


def login_page(request):
    user = request.user
    # if user.is_authenticated:
    #     return redirect("favigen:home")

    if request.POST:
        form = CustomAuthenticationForm(request.POST)
        email = request.POST.get("email")
        password = request.POST.get("password")

        if user := authenticate(email=email, password=password):
            login(request, user)
            messages.success(request, "Logged In")
            return redirect("favigen:home")
        else:
            messages.error(request, "Please enter correct details")
    else:
        form = CustomAuthenticationForm()

    context = {"login_form": form}
    return render(request, "favigen/login.html", context)


def logout_view(request):
    logout(request)
    messages.success(request, "Logged Out")
    return redirect("favigen:login")


def contact_page(request):
    user = request.user
    context = {}

    if request.method == 'POST':
        subject = request.POST.get('subject')
        email = request.POST.get('email')
        message = request.POST.get('subject')
        priority = request.POST.get('priority')

        message = Message.objects.create(
            title=subject,
            user=user,
            email=email,
            message=message,
            priority=priority,
        )
        message.save()
        return redirect("favigen:sent")
    return render(request, "favigen/contact.html", context)


def message_sent(request):
    return render(request, "favigen/message_sent.html")


@login_required(login_url='fav:login')
def saved_icons(request):
    user = request.user
    current_user_email = user.email
    favicons = Favicon.objects.all()

    context = {'favicons': favicons}
    return render(request, "favigen/saved-icons.html", context)


@login_required(login_url='fav:login')
def generated_icon(request, pk):
    user=request.user
    favicon = Favicon.objects.get(id=pk)

    context = {'favicon': favicon}
    return render(request, "favigen/generated-icon.html", context)


@login_required(login_url='fav:login')
def generate_icon(request):
    user = request.user
    context = {}

    if request.method == "POST":
        image_file = request.FILES["document"]
        title = request.POST.get("title")
        favourite = bool(request.POST.get("favourite"))

        fs = FileSystemStorage()
        name = fs.save(name=image_file.name, content=image_file)
        url_img = fs.url(name)

        file_path = f"static/media/{image_file.name}"
        favs_dir = "static/media/favs/"
        f_type = image_file.name.split(".")[-1]
        f_size = os.path.getsize(file_path)

        # Get current date and add the string prefix "FAV" to it
        a = f"FAV{str(datetime.now())}"
        # Remove special chacracters and spaces from the date string
        b = ''.join(re.split(r'-|\.|:|\ ', a))
        # Combine the date string with file extension to form new file name
        new_name = f"{b}.{f_type}"

        # Generate favicons and zip them
        embed_link = generate_favicon(file_path, favs_dir)

        img = Image.objects.create(
            title=title,
            uploaded_image=image_file,
            favourite=favourite,
            uploaded_by=user)
        img.save()

        # Create the zipped file
        user_dir = f"static/media/user_{user.id}"
        zippify.zippify(favs_dir, user_dir, b)


        fav = Favicon.objects.create(
            image=img,
            original_filename=name, 
            new_filename=new_name,
            file_type=f_type,
            file_byte_size=f_size,
            embed_link=embed_link)
        fav.save()

        saved_fav = Favicon.objects.get(new_filename=new_name)
        path = Path(os.path.join(user_dir, f"{b}.zip"))
        with path.open(mode='rb') as f:
            saved_fav.zipped_favs = File(f, name=path.name)
            saved_fav.save()

        # Delete generated favicons after zipping them
        utility.delete(favs_dir)

        # Get the object of the current favicon from the database
        saved_zip = Favicon.objects.filter(new_filename=new_name)

        context["url_img"] = url_img
        context["url_zip"] = saved_zip

        return redirect("favigen:generated", pk=saved_fav.id)
    return render(request, "favigen/generate-icon.html")

favigen/templates/favigen/generate.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Generate Icons Page</title>
        <link href="{% static '/favigen/css/generate.css' %}" rel="stylesheet" />
        <link
            href="https://fonts.googleapis.com/css2?family=Manrope:wght@600&family=Poppins:wght@400;500;600;700&display=swap"
            rel="stylesheet"
        />
    </head>
    <body>
        <div class="container1">
            <div class="container2">
                <div class="header">
                    <div class="logo">
                        <img src="{% static '/favigen/img/smalllogo.svg' %}" alt="logo" />
                    </div>
                    <div class="nav-menu">
                        <nav class="nav">
                            <a class="a" href="{% url 'fav:home' %}">Home</a>
                            <a class="a" href="{% url 'fav:contact' %}">Contact Us</a>
                            <a class="a" href="{% url 'fav:saved' %}">Saved Icons</a>
                            <a class="a" href="{% url 'fav:generate' %}">Generate</a>
                            {% if user.is_authenticated %}
                            <a class="a" href="{% url 'fav:logout' %}">Log Out</a>
                            {% else %}
                            <a class="a" href="{% url 'fav:login' %}">Sign In</a>
                            {% endif %}
                        </nav>
                    </div>
                    <div class="hamburger">
                        <span class="bar"></span>
                        <span class="bar"></span>
                        <span class="bar"></span>
                    </div>
                </div>
            </div>
        </div>

        <main>
            <div class="div2">
                <div class="generate">
                    <button class="btn_generate" type="button">
                        <a class="b" href="{% url 'fav:generate' %}">Generated</a>
                    </button>
                    <button class="btn_saved" type="button">
                        <a class="b" href="{% url 'fav:saved' %}">Saved Icons</a>
                    </button>
                </div>
                <br /><br />

                <div class="div2b">
                    <label class="labelproject" for="Project name">Project name</label>
                    <input size="50" placeholder="git lab" type="textarea" class="inputgit" />
                </div>
            </div>
        </main>

        <section>
            <div class="file">
                <img src="{% static '/favigen/img/vector.png' %}" alt="" />
                <p class="drag">Drag and drop your files here <br /><span>OR</span> <br /></p>
                <button>click here to upload.</button>
                <input type="file" hidden />
                <script src="{% static '/favigen/js/index.js' %}"></script>
            </div>

            <div class="div3">
                <div class="div3a">
                    <p class="text1"><b>Or Add text here</b></p>
                </div>
                <br />
                <div class="div3b"><input class="place" type="textarea" size="30" /></div>
            </div>
            <br />

            <div class="div4">
                <input class="check" type="checkbox" />
                <label for="Code">Generate Embedded Html code</label>
            </div>
            <br /><br />

            <div class="div5">
                <button class="button1"><a href="#">Generate</a></button>
            </div>
        </section>
    </body>
</html>

favigen/templates/favigen/saved-icons.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="{% static 'favigen/img/logo.svg' %}" />
        <title>Saved Icons</title>
        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx"
            crossorigin="anonymous"
        />
        <link
            href="https://fonts.googleapis.com/css2?family=Manrope:wght@600&family=Poppins:wght@400;500;600;700&display=swap"
            rel="stylesheet"
        />
        <link href="{% static '/favigen/css/saved-icons.css' %}" rel="stylesheet" />
    </head>

    <body>
        <main>
            <div class="container1">
                <div class="container2 position-relative">
                    <nav class="navbar navbar-expand-lg">
                        <div class="container-fluid px-3">
                            <a class="navbar-brand" href="{% url 'fav:home' %}">
                                <img
                                    src="{% static 'favigen/img/logo.svg' %}"
                                    width="30"
                                    class="d-inline-block align-top"
                                    alt="logo"
                                />
                            </a>
                            <button
                                class="navbar-toggler"
                                type="button"
                                data-bs-toggle="collapse"
                                data-bs-target="#navbarText"
                                aria-controls="navbarText"
                                aria-expanded="false"
                                aria-label="Toggle navigation"
                            >
                                <span class="navbar-toggler-icon"></span>
                            </button>
                            <div class="collapse navbar-collapse" id="navbarText">
                                <ul class="navbar-nav mx-auto mb-2 mb-lg-0">
                                    <li class="nav-item">
                                        <a class="nav-link" href="{% url 'fav:home' %}">Home</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="{% url 'fav:contact' %}">Contact Us</a>
                                    </li>
                                    <li class="nav-item">
                                        {% if user.is_authenticated %}
                                        <a
                                            class="nav-link active"
                                            aria-current="page"
                                            href="{% url 'fav:saved' %}"
                                            >Saved Icons</a
                                        >
                                        {% endif %}
                                    </li>
                                    <li class="nav-item">
                                        {% if user.is_authenticated %}
                                        <a class="nav-link" href="{% url 'fav:generate' %}">Generate</a>
                                        {% endif %}
                                    </li>
                                    <li class="nav-item">
                                        {% if user.is_authenticated %}
                                        <a class="nav-link" href="{% url 'fav:logout' %}">Log Out</a>
                                        {% else %}
                                        <a class="nav-link" href="{% url 'fav:login' %}">Sign In</a>
                                        {% endif %}
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </nav>

                    <div class="generate">
                      <a class="b" href="{% url 'fav:generate' %}">
                        <button class="btn_generate" type="button">
                            Generate
                        </button>
                      </a>
                      <a class="b" href="{% url 'fav:saved' %}">
                        <button class="btn_saved" type="button">
                            Saved Icons
                        </button>
                      </a>
                    </div>

                    <div class="savedi">
                        <div class="savedi1">
                            <form action="#" method="get">
                                <button type="submit">
                                    <img src="{% static '/favigen/img/search.svg' %}" alt="search" />
                                </button>
                                <input type="text" placeholder="Search your saved icons" name="q" />
                            </form>
                        </div>
                        <div class="savedi2">
                            <h2 class="p1">Recent:</h2>
                          {% if favicons %}
                            {% for fav in favicons %}
                            <a href="{% url 'fav:generated' fav.id %}">
                            <img
                                class="img1"
                                src="{{ fav.image.uploaded_image.url }}"
                                alt="{{ favicon.image.title }}"
                                width="100"
                                height="100"
                            />
                            {% endfor %}
                            </a>
                          {% endif%}
                        </div>
                    </div>
                </div>

                <div class="container3">
                    <div>
                        <h1 class="h1" id="h1">Collections</h1>
                    </div>

                    <div class="icons">
                        <div class="icons1">
                            <h2 class="h2">Favourite Icons</h2>
                            <div class="parent1">
                                <div>
                                    <img
                                        class="img2"
                                        src="{% static '/favigen/img/icon1.png' %}"
                                        alt=""
                                    /><img
                                        class="img2"
                                        src="{% static '/favigen/img/icon5.png' %}"
                                        alt=""
                                    /><img
                                        class="img2"
                                        src="{% static '/favigen/img/icon10.png' %}"
                                        alt=""
                                    /><img
                                        class="img2"
                                        src="{% static '/favigen/img/icon13.png' %}"
                                        alt=""
                                    /><img class="img2" src="{% static '/favigen/img/icon18.png' %}" alt="" />
                                </div>
                                <div>
                                    <img
                                        class="img2"
                                        src="{% static '/favigen/img/icon5.png' %}"
                                        alt=""
                                    /><img
                                        class="img2"
                                        src="{% static '/favigen/img/icon6.png' %}"
                                        alt=""
                                    /><img
                                        class="img2"
                                        src="{% static '/favigen/img/icon9.png' %}"
                                        alt=""
                                    /><img
                                        class="img2"
                                        src="{% static '/favigen/img/icon11.png' %}"
                                        alt=""
                                    /><img class="img2" src="{% static '/favigen/img/icon14.png' %}" alt="" />
                                </div>
                            </div>
                            <b class="b">50 saved</b>
                        </div>

                        <div class="icons2">
                            <h2 class="h2">Brand Icons</h2>
                            <div class="parent2">
                                <div>
                                    <img
                                        class="img2"
                                        src="{% static '/favigen/img/icon16.png' %}"
                                        alt=""
                                    /><img
                                        class="img2"
                                        src="{% static '/favigen/img/icon7.png' %}"
                                        alt=""
                                    /><img
                                        class="img2"
                                        src="{% static '/favigen/img/icon3.png' %}"
                                        alt=""
                                    /><img
                                        class="img2"
                                        src="{% static '/favigen/img/icon12.png' %}"
                                        alt=""
                                    /><img class="img2" src="{% static '/favigen/img/icon1.png' %}" alt="" />
                                </div>
                                <div>
                                    <img
                                        class="img2"
                                        src="{% static '/favigen/img/icon12.png' %}"
                                        alt=""
                                    /><img
                                        class="img2"
                                        src="{% static '/favigen/img/icon13.png' %}"
                                        alt=""
                                    /><img
                                        class="img2"
                                        src="{% static '/favigen/img/icon18.png' %}"
                                        alt=""
                                    /><img
                                        class="img2"
                                        src="{% static '/favigen/img/icon10.png' %}"
                                        alt=""
                                    /><img class="img2" src="{% static '/favigen/img/icon5.png' %}" alt="" />
                                </div>
                            </div>
                            {% comment %}
                            <h2 class="h22">...</h2>
                            {% endcomment %}
                        </div>
                    </div>

                    <div class="fav_icon">
                        <h2 class="h2">Favourite Icons</h2>
                        <div>
                            <img class="img2" src="{% static '/favigen/img/icon8.png' %}" alt="" /><img
                                class="img2"
                                src="{% static '/favigen/img/icon4.png' %}"
                                alt=""
                            /><img class="img2" src="{% static '/favigen/img/icon8.png' %}" alt="" /><img
                                class="img2"
                                src="{% static '/favigen/img/icon17.png' %}"
                                alt=""
                            /><img class="img2" src="{% static '/favigen/img/icon4.png' %}" alt="" /><img
                                class="img2"
                                src="{% static '/favigen/img/icon8.png' %}"
                                alt=""
                            />
                        </div>
                    </div>
                </div>
            </div>
        </main>
        <script
            src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.0/js/bootstrap.min.js"
            integrity="sha512-8Y8eGK92dzouwpROIppwr+0kPauu0qqtnzZZNEF8Pat5tuRNJxJXCkbQfJ0HlUG3y1HB3z18CSKmUo7i2zcPpg=="
            crossorigin="anonymous"
            referrerpolicy="no-referrer"
        ></script>
    </body>
</html>